apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  namespace: dljobs
  name: seq2seq
spec:
  runPolicy:
    cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              command: ["python", "Seq2Seq.py"]
              args: ["--batch_size", "16", "--learning_rate", "0.0001", "--epochs", "3", "--data_percentage", "0.2", "--workload_name", "seq2seq", "--data_dir", "/train"]
              image: 10.170.23.190:8081/dljob/seq2seq:v1.0
              volumeMounts:
                - mountPath: /train
                  name: training
              resources:
                limits:
                  aliyun.com/gpu-mem: 5
          volumes:
            - name: training
              persistentVolumeClaim:
                claimName: test-pvc
