# By DCJ, XDU
# 开发时间：2023/11/11 PM 08:33
command = {
    "audio_classification" : [
        "python",
        "run_audio_classification.py",
        "--model_name_or_path = facebook/wav2vec2-base",
        "--dataset_name = superb",
        "--dataset_config_name = ks",
        "--output_dir = wav2vec2-base-ft-keyword-spotting",
        "--overwrite_output_dir",
        "--remove_unused_columns = False",
        "--do_train",
        "--do_eval",
        "--fp16",
        "--learning_rate = 3e-5",
        "--max_length_seconds = 1",
        "--attention_mask = False",
        "--warmup_ratio = 0.1",
        "--num_train_epochs = 5",
        "--per_device_train_batch_size = 32",
        "--gradient_accumulation_steps = 4",
        "--per_device_eval_batch_size = 32",
        "--dataloader_num_workers = 4",
        "--logging_strategy = steps",
        "--logging_steps = 10",
        "--evaluation_strategy = epoch",
        "--save_strategy = epoch",
        "--load_best_model_at_end = True",
        "--metric_for_best_model = accuracy",
        "--save_total_limit = 3",
        "--seed = 0"
    ],
    "image_classification" : [
            "python",
            "/training_script/image_classification_training_script/run_image_classification.py",
            "--model_name_or_path=/treasures/model",
            "--train_dir=/treasures/data",
            "--output_dir=/treasures/output/",
            "--remove_unused_columns=False",
            "--do_train",
            "--do_eval",
            "--learning_rate=2e-5",
            "--num_train_epochs=5",
            "--per_device_train_batch_size=8",
            "--per_device_eval_batch_size=8",
            "--logging_strategy=steps",
            "--logging_steps=10",
            "--evaluation_strategy=epoch",
            "--save_strategy=epoch",
            "--load_best_model_at_end=False",
            "--save_total_limit=3",
            "--seed=1337",
            "--ignore_mismatched_sizes=True",
            "--overwrite_output_dir=True"
        ],
    "image_pretraining" : [
            "python",
            "run_mim.py",
            "--model_name_or_path = google/vit-base-patch16-224-in21k",
            "--output_dir = ./outputs/",
            "--overwrite_output_dir",
            "--remove_unused_columns  = False",
            "--label_names = bool_masked_pos",
            "--do_train",
            "--do_eval",
            "--learning_rate = 2e-5",
            "--weight_decay = 0.05",
            "--num_train_epochs = 100",
            "--per_device_train_batch_size = 8",
            "--per_device_eval_batch_size = 8",
            "--logging_strategy = steps",
            "--logging_steps = 10",
            "--evaluation_strategy = epoch",
            "--save_strategy = epoch",
            "--load_best_model_at_end = True",
            "--save_total_limit = 3",
            "--seed = 1337"
    ],
    "language_modeling" : [
            "python",
            "run_clm.py",
            "--model_name_or_path = gpt2",
            "--dataset_name = wikitext",
            "--dataset_config_name = wikitext-2-raw-v1",
            "--per_device_train_batch_size = 8",
            "--per_device_eval_batch_size = 8",
            "--do_train",
            "--do_eval",
            "--output_dir = /tmp/test-clm"
    ],
    "mutiple_choice" : [
            "python",
            "run_swag.py",
            "--model_name_or_path = roberta-base",
            "--do_train",
            "--do_eval",
            "--learning_rate = 5e-5",
            "--num_train_epochs = 3",
            "--output_dir = /tmp/swag_base",
            "--per_device_eval_batch_size = 16",
            "--per_device_train_batch_size = 16",
            "--overwrite_output"
    ],
    "question_answering" : [
            "python",
            "run_qa.py",
            "--model_name_or_path = bert-base-uncased",
            "--dataset_name = squad",
            "--do_train",
            "--do_eval",
            "--per_device_train_batch_size = 12",
            "--learning_rate = 3e-5",
            "--num_train_epochs = 2",
            "--max_seq_length = 384",
            "--doc_stride = 128",
            "--output_dir = /tmp/debug_squad/"
    ]
}
