apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  namespace: dljobs
  name: dcgan
spec:
  runPolicy:
    cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          schedulerName: my-scheduler
          containers:
            - name: tensorflow
              command: ["python", "DCGAN.py"]
              args: ["--batch_size", "16", "--learning_rate", "0.0001", "--epochs", "50", "--data_percentage", "1", "--workload_name", "dcgan", "--data_dir", "/train"]
              image: 10.170.23.190:8081/dljob/dcgan:v1.0
              volumeMounts:
                - mountPath: /train
                  name: training
              resources:
                limits:
                  aliyun.com/gpu-mem: 10
          volumes:
            - name: training
              persistentVolumeClaim:
                claimName: test-pvc