apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  namespace: dljobs
  name: unet
spec:
  runPolicy:
    cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 3
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: 10.170.23.190:8081/dljob/unet:v1.0
              command: ["python", "UNet.py"]
              args: ["--batch_size", "16", "--learning_rate", "0.0001", "--epochs", "100", "--data_percentage", "0.5", "--workload_name", "unet", "--data_dir", "/train"]
              volumeMounts:
                - mountPath: /train
                  name: training
              resources:
                limits:
                  aliyun.com/gpu-mem: 4
          volumes:
            - name: training
              persistentVolumeClaim:
                claimName: test-pvc
