server:
  ip: 124.70.188.119  # master ip
  port: 32081
spring:
  datasource:
    dynamic:
      datasource:
        mysql:
          url: jdbc:mysql://124.70.188.119:3307/automl?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: bdilab@1308
  redis:
    host: 124.70.188.119
    port: 6379
    password: bdilab@1308

kubernetes:
  config:
    path: /root/.kube/config

istio:
  ingressgateway:
    ip: 124.70.188.119
    port: 32300
